USE ODEV_1;
DROP TABLE IF EXISTS Kategoriler,Yazarlar
CREATE TABLE Kategoriler
(
	KategoriAdi NVARCHAR(64) UNIQUE DEFAULT 'Genel' 
);
CREATE TABLE Yazarlar
(
	YazarID TINYINT IDENTITY(1,1)  NOT NULL,
	YazarAdi NVARCHAR(64) NOT NULL,
	YazarSoyadi NVARCHAR(32) NOT NULL,
	Email NVARCHAR(128) NOT NULL,
	BirthDate Date,
	PRIMARY KEY(YazarID)

);
CREATE TABLE Makaleler
(
	MakaleAdi NVARCHAR(140) NOT NULL,
	Kategori NVARCHAR(64) DEFAULT 'Genel' NOT NULL,
	MakaleIcerik NVARCHAR(MAX),
	EklenmeTarihi DATETIME DEFAULT(SYSDATETIME()) NOT NULL,
	YazarID TINYINT NOT NULL,
	YazarAdi NVARCHAR(64) NOT NULL,
	YazarSoyadi NVARCHAR(32) NOT NULL
	CONSTRAINT FK_YazarID
		FOREIGN KEY(YazarID) REFERENCES Yazarlar(YazarID)
		ON DELETE NO ACTION
		ON UPDATE CASCADE,
	CONSTRAINT FK_KategoriAdi
		FOREIGN KEY(Kategori) REFERENCES Kategoriler(KategoriAdi)
		ON UPDATE CASCADE
		ON DELETE SET DEFAULT

);

